#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - cd application
  - npm install

script:
  - ng test --single-run --watch=false
  - ng build --prod 

after_success:
  - echo 'BUILD SUCCESS'

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    branch: "master"