#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install
  - npm install -g @angular/cli
  - cd front-end
  - npm install
  - cd ../back-end
  - npm install

script:
  - echo "$TRAVIS_BRANCH"
  - ng build --prod

# TODO: Deployment
# deploy:
#   provider: "heroku"

after_success:
  - echo 'BUILD SUCCESS'
